name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build-stats:
    name: Update stats SVG
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: jstrieb/github-stats@master
        with:
          username: Shriradhakrishnasharnam
          exclude_repos: ""
          exclude_langs: ""
          include_all_commits: true
          show_languages: true
          hide_border: true
          card_width: 500
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
